// GENERATED CONTENT — Tulare County directory ported from the Adelante Journey
// build. Every entry lands UNVERIFIED on purpose: sourced from public listings,
// so it stays out of the patient-facing list until a named staff member
// confirms address, phone and hours through `verifyResource`. Entries this
// project already sourced by hand are not duplicated here.
import type { CommunityResource } from "@/lib/communityResources";

export const PORTED_RESOURCES: CommunityResource[] = [
  {
    "id": "res_loop_bus",
    "categoryId": "transportation",
    "name": "LOOP Bus",
    "address": "Countywide, through community programs, Tulare County, CA",
    "phone": "Verify number",
    "hours": "Verify schedule",
    "description": "Free transit for at-risk youth, offered through community-based programs. Ask your case manager whether you or your kids qualify.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_medi_cal_rides",
    "categoryId": "transportation",
    "name": "Medi-Cal Non-Emergency Medical Transportation",
    "address": "Through your Medi-Cal plan, California",
    "phone": "Call the number on your Medi-Cal card",
    "hours": "Mon–Fri (verify with plan)",
    "website": "https://www.dhcs.ca.gov",
    "description": "If you have Medi-Cal, your plan may cover free rides to medical and behavioral health appointments.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_kings_view_sud",
    "categoryId": "recovery_meetings",
    "name": "Kings View Substance Abuse Program",
    "address": "559 E. Bardsley Ave, Tulare, CA 93274",
    "phone": "(559) 687-8000",
    "hours": "Mon–Fri, 8:00am – 5:00pm (verify)",
    "website": "https://kingsview.org",
    "description": "Outpatient substance use treatment, groups, and case management in Tulare. (Kings View is the organization's name — the program serves Tulare County.)",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_turning_point_1stop",
    "categoryId": "recovery_meetings",
    "name": "Turning Point North County 1-Stop",
    "address": "201 N. K St, Tulare, CA 93274",
    "phone": "(559) 686-6771",
    "hours": "Mon–Fri, 8:00am – 5:00pm (verify)",
    "website": "https://www.tpocc.org",
    "description": "Groups, case management, and court-related classes (this is the same site listed for your anger management group on the Obligations screen).",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_aa_central_valley",
    "categoryId": "recovery_meetings",
    "name": "Alcoholics Anonymous – Central Valley (Tulare County meetings)",
    "address": "Meetings across Visalia, Tulare, Porterville, Dinuba, Tulare County, CA",
    "phone": "(559) 570-5464",
    "hours": "Daily meetings, morning through evening",
    "website": "https://www.aacentralvalley.org",
    "description": "AA meetings all over the county, most days of the week. Check the current schedule before you go.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_na_central_valley",
    "categoryId": "recovery_meetings",
    "name": "Narcotics Anonymous – Central Valley Area",
    "address": "Meetings across Tulare County, Tulare County, CA",
    "phone": "(559) 224-5800",
    "hours": "Daily meetings (verify schedule)",
    "website": "https://www.centralvalleyna.org",
    "description": "NA meetings across the county, including evening options. Newcomers are welcome and nobody has to speak.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_smart_recovery",
    "categoryId": "recovery_meetings",
    "name": "SMART Recovery (online + regional meetings)",
    "address": "Online and in-person meetings, California",
    "phone": "",
    "hours": "Daily online meetings",
    "website": "https://meetings.smartrecovery.org",
    "description": "Science-based recovery support group. Good option if 12-step isn't your thing, and online meetings run around the clock.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_geo_reentry_sort",
    "categoryId": "support_groups",
    "name": "GEO Reentry – Tulare County SORT",
    "address": "Near Tulare County Probation Adult Division, Visalia, CA",
    "phone": "Verify number",
    "hours": "Mon–Fri (verify)",
    "website": "https://www.georeentry.com",
    "description": "Supervised Opportunity and Resource Team — community navigation, targeted interventions, and referrals for housing, health, and counseling after release.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_kings_view_mh",
    "categoryId": "support_groups",
    "name": "Kings View Mental Health Services",
    "address": "201 N. K St, Tulare, CA 93274",
    "phone": "(559) 687-8000",
    "hours": "Mon–Fri, 8:00am – 5:00pm (verify)",
    "website": "https://kingsview.org",
    "description": "Counseling, groups, and mental health case management. (Kings View is the org's name, not a county.)",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_namilulare",
    "categoryId": "support_groups",
    "name": "NAMI Tulare County",
    "address": "Verify address, Visalia, CA",
    "phone": "Verify number",
    "hours": "Weekly peer and family groups (verify)",
    "website": "https://namica.org",
    "description": "Free peer-led support groups for people living with mental health conditions, plus groups for family members.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_tc_behavioral_health",
    "categoryId": "support_groups",
    "name": "Tulare County Mental Health Crisis & Support Line",
    "address": "5957 S. Mooney Blvd, Visalia, CA 93277",
    "phone": "1-800-320-1616",
    "hours": "24/7 crisis line",
    "website": "https://tchhsa.org",
    "description": "County behavioral health — 24/7 crisis line, therapy, psychiatry, and case management.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_family_services_tulare",
    "categoryId": "family_reunification",
    "name": "Family Services of Tulare County",
    "address": "815 W. Oak Ave, Visalia, CA 93291",
    "phone": "(559) 732-5941",
    "hours": "Mon–Fri, 8:00am – 5:00pm; 24/7 crisis line",
    "website": "https://www.fstc.net",
    "description": "Trauma-informed domestic violence services, counseling, and in-person victim response across the county.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_calworks_tulare",
    "categoryId": "family_reunification",
    "name": "CalWORKs (Tulare County)",
    "address": "Offices in Lindsay, Porterville, Visalia, Tulare, Dinuba, Tulare County, CA",
    "phone": "1-877-410-8813",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://tularecounty.ca.gov",
    "description": "Cash aid and support services for families with children. State program, county offices — apply at whichever office is closest.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_child_welfare_reunification",
    "categoryId": "family_reunification",
    "name": "Tulare County Child Welfare Services – Reunification",
    "address": "3500 W. Mineral King Ave, Visalia, CA 93291",
    "phone": "(559) 623-0700",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://tchhsa.org",
    "description": "Case workers who handle reunification plans, visitation, and the steps required to get your kids back home.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_kaweah_health",
    "categoryId": "healthcare",
    "name": "Kaweah Health Medical Center",
    "address": "400 W. Mineral King Ave, Visalia, CA 93291",
    "phone": "(559) 624-2000",
    "hours": "24/7 emergency; clinics Mon–Fri",
    "website": "https://www.kaweahhealth.org",
    "description": "Main hospital system for Tulare County, with clinics in several cities. Emergency care regardless of ability to pay.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_medi_cal_tulare",
    "categoryId": "healthcare",
    "name": "Medi-Cal (Tulare County)",
    "address": "Offices in Visalia, Tulare, Porterville, Dinuba, Lindsay, Tulare County, CA",
    "phone": "1-877-410-8813",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://tularecounty.ca.gov",
    "description": "Free or low-cost health coverage. Most people leaving custody qualify — you can apply the same week you're out.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_altura_centers",
    "categoryId": "healthcare",
    "name": "Altura Centers for Health",
    "address": "1095 E. Prosperity Ave, Tulare, CA 93274",
    "phone": "(559) 686-8677",
    "hours": "Mon–Fri (verify hours)",
    "website": "https://alturacenters.org",
    "description": "Community health centers — primary care, behavioral health, and dental on a sliding scale.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_family_healthcare_network",
    "categoryId": "healthcare",
    "name": "Family HealthCare Network",
    "address": "Clinics countywide, Tulare County, CA",
    "phone": "1-877-960-3426",
    "hours": "Mon–Sat (verify by clinic)",
    "website": "https://www.fhcn.org",
    "description": "Clinics across the county for primary care, MAT, behavioral health, and dental. Sliding-scale fees and Medi-Cal accepted.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_college_of_sequoias",
    "categoryId": "education",
    "name": "College of the Sequoias",
    "address": "915 S. Mooney Blvd, Visalia, CA 93277",
    "phone": "(559) 730-3700",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://www.cos.edu",
    "description": "Community college with campuses in Visalia, Hanford, and Tulare. Certificates, degrees, and free tuition for many first-year students.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_tcoe_adult_education",
    "categoryId": "education",
    "name": "Tulare County Office of Education – Adult Education & HiSET/GED",
    "address": "6200 S. Mooney Blvd, Visalia, CA 93277",
    "phone": "(559) 733-6300",
    "hours": "Mon–Fri (verify class times)",
    "website": "https://tcoe.org",
    "description": "Free adult education, high school equivalency prep, and testing across Tulare County.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_porterville_college",
    "categoryId": "education",
    "name": "Porterville College",
    "address": "100 E. College Ave, Porterville, CA 93257",
    "phone": "(559) 791-2200",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://www.portervillecollege.edu",
    "description": "Community college in the south county with certificate programs and transfer degrees.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_adult_school_tulare",
    "categoryId": "education",
    "name": "Tulare Adult School",
    "address": "1100 E. Bardsley Ave, Tulare, CA 93274",
    "phone": "(559) 687-7320",
    "hours": "Day and evening classes (verify)",
    "website": "https://www.tulare.k12.ca.us",
    "description": "Free GED prep, English classes, and career training with evening options if you work days.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_cset_head_start",
    "categoryId": "parenting",
    "name": "CSET Head Start / Early Head Start",
    "address": "312 NW 3rd Ave, Visalia, CA 93291",
    "phone": "(559) 741-4640",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://www.cset.org",
    "description": "Free preschool and childcare for kids 0–5, plus family support for parents getting back on their feet.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_tulare_first_5",
    "categoryId": "parenting",
    "name": "First 5 Tulare County",
    "address": "4949 W. Cypress Ave, Visalia, CA 93277",
    "phone": "(559) 622-8650",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://www.first5tulare.org",
    "description": "Parenting classes, early childhood support, and family resource centers around the county.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_parenting_network",
    "categoryId": "parenting",
    "name": "The Parenting Network",
    "address": "323 N. Johnson St, Visalia, CA 93291",
    "phone": "(559) 625-0384",
    "hours": "Mon–Fri, 8:30am – 5:00pm (verify)",
    "website": "https://parentingnetwork.org",
    "description": "Parenting classes (including court-approved ones), home visits, and a parent warmline for hard days.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_california_lifeline",
    "categoryId": "financial",
    "name": "California LifeLine – Discounted Phone & Internet",
    "address": "Statewide program — apply online or by mail, California",
    "phone": "1-866-272-0349",
    "hours": "Mon–Fri, 7:00am – 7:00pm",
    "website": "https://www.californialifeline.com/en",
    "description": "State program that gets you a discounted (often free) cell phone and service if you're low-income or on benefits like Medi-Cal or CalFresh. A working phone is how everything else gets easier.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_general_assistance_tulare",
    "categoryId": "financial",
    "name": "General Assistance (Tulare County)",
    "address": "Offices in Visalia, Tulare, Porterville, Dinuba, Lindsay, Tulare County, CA",
    "phone": "1-877-410-8813",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://tularecounty.ca.gov",
    "description": "County-funded cash aid for adults without children who don't qualify for other programs. Small amount, but it's something while you get set up.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_social_security_admin",
    "categoryId": "financial",
    "name": "Social Security Administration – SSI / SSDI",
    "address": "5040 W. Cypress Ave, Visalia, CA 93277",
    "phone": "1-800-772-1213",
    "hours": "Mon–Fri, 9:00am – 4:00pm",
    "website": "https://www.ssa.gov",
    "description": "Disability and supplemental income benefits. Worth applying if a health condition limits your ability to work.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_cset_utility_liheap",
    "categoryId": "financial",
    "name": "CSET Utility Assistance (LIHEAP)",
    "address": "312 NW 3rd Ave, Visalia, CA 93291",
    "phone": "(559) 741-4640",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://www.cset.org",
    "description": "Help paying past-due utility bills so the power stays on while you're getting stable.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_central_cal_legal",
    "categoryId": "legal",
    "name": "Central California Legal Services – Record Expungement Clinic",
    "address": "208 W. Main St, Suite U-1, Visalia, CA 93291",
    "phone": "(559) 733-8770",
    "hours": "Mon–Fri, 9:00am – 5:00pm (clinic days vary)",
    "website": "https://centralcallegal.org",
    "description": "Free legal information on expungement eligibility and record clearing, serving Tulare plus Fresno, Kings, Madera, Merced, Mariposa, and Tuolumne counties.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_tulare_court_self_help",
    "categoryId": "legal",
    "name": "Tulare County Superior Court Self-Help Center",
    "address": "221 S. Mooney Blvd, Visalia, CA 93291",
    "phone": "(559) 730-5000",
    "hours": "Mon–Fri (verify walk-in hours)",
    "website": "https://tularecounty.ca.gov",
    "description": "Free help with court forms — custody, child support, expungement, fee waivers — if you don't have a lawyer.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_tulare_public_defender",
    "categoryId": "legal",
    "name": "Tulare County Public Defender",
    "address": "800 S. Akers St, Visalia, CA 93277",
    "phone": "(559) 636-4500",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://tularecounty.ca.gov",
    "description": "Representation on open cases and, in some situations, help with post-conviction relief and record clearance.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_dmv_id_tulare",
    "categoryId": "legal",
    "name": "California DMV – Replacement ID Card",
    "address": "1445 N. Ben Maddox Way, Visalia, CA 93292",
    "phone": "1-800-777-0133",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://www.dmv.ca.gov",
    "description": "Get a state ID card — reduced-fee IDs are available if you're low-income or recently released. Make an appointment online to skip the line.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_tulare_probation_adult",
    "categoryId": "legal",
    "name": "Tulare County Probation – Adult Division",
    "address": "5957 S. Mooney Blvd, Visalia, CA 93277",
    "phone": "(559) 730-2540",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://www.tcprobation.com",
    "description": "Beyond supervision: help with medical and mental health referrals, Medi-Cal applications, and employment or education goals.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_cset_life_skills",
    "categoryId": "life_skills",
    "name": "CSET Life Skills & Financial Coaching",
    "address": "312 NW 3rd Ave, Visalia, CA 93291",
    "phone": "(559) 741-4640",
    "hours": "Mon–Fri, 8:00am – 5:00pm",
    "website": "https://www.cset.org",
    "description": "Budgeting, banking, and daily-living workshops, plus one-on-one coaching to build savings and credit.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_goodwill_industries",
    "categoryId": "life_skills",
    "name": "Goodwill Industries – Career & Life Skills Center",
    "address": "1441 W. Main St, Visalia, CA 93291",
    "phone": "(559) 732-1976",
    "hours": "Mon–Fri, 9:00am – 5:00pm (verify)",
    "website": "https://www.goodwill.org",
    "description": "Computer basics, resume help, interview practice, and work clothes if you need them for an interview.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  },
  {
    "id": "res_salvation_army_visalia",
    "categoryId": "life_skills",
    "name": "The Salvation Army – Visalia Corps",
    "address": "1500 W. Main St, Visalia, CA 93291",
    "phone": "(559) 741-1006",
    "hours": "Mon–Fri (verify hours)",
    "website": "https://visalia.salvationarmy.org",
    "description": "Practical support — meals, clothing, life skills classes, and case management for people rebuilding.",
    "placeholder": false,
    "verified": false,
    "status": "unverified"
  }
];
