// Spanish player copy is Draft — pending bilingual clinical sign-off.
export const playerEn = {
  playerBreathingType: "Breathing", playerTimerType: "Timer", playerChecklistType: "Checklist", playerWorksheetType: "Worksheet", playerMapperType: "Map", playerCalculatorType: "Calculator", playerScaleType: "Scale", playerSeconds: "seconds", playerLibraryBack: "Back to the library",
  playerConfidenceStart: "Choose a confidence rating",
  playerListen: "Listen", playerVoice: "Read aloud (Simulated voice)", playerSlow: "Slow", playerNormal: "Normal", playerReplay: "Replay", playerStop: "Stop", playerVoiceOff: "Read aloud off", playerVoiceUnavailable: "Read aloud is not available on this device.",
  playerDraft: "Spanish — Draft", playerInhale: "Breathe in", playerHold: "Hold", playerExhale: "Breathe out", playerCycle: "Cycle", playerOf: "of", playerStart: "Start", playerPause: "Pause", playerDone: "Done", playerReset: "Reset", playerCues: "Spoken breathing cues", playerRounds: "rounds of breathing", playerSave: "Save to My Toolkit", playerSaved: "Saved to My Toolkit", playerPurpose: "Purpose", playerMinutes: "minutes", playerRemove: "Remove", playerAdd: "Add", playerLeft: "Left over", playerMoneyIn: "In", playerMoneyOut: "out", playerMoneyLeft: "left", playerResponses: "Your practice is saved.",
  playerSee: "see", playerFeel: "feel", playerHear: "hear", playerSmell: "smell", playerTaste: "taste", playerThings: "Things you can", playerBack: "Back", playerNext: "Next", playerQuestion: "Question", playerReply: "Thank you for sharing. One small step is enough for today.", playerQuestion2: "What could make this easier for you?", playerQuestion3: "What small step would you like to try?", playerSuggests: "Adel suggests next", playerKeepTalking: "Keep talking with Adel", playerSimulated: "Simulated — Draft", playerAnswer: "Your answer", playerSend: "Share answer", playerToday: "Choose one action for today", playerTodayHome: "Today's action", playerConfidence: "How confident do you feel?", playerUnanswered: "Not answered", playerPreview: "Your toolkit save preview", playerTool: "Tool", playerNextStep: "Next step", playerReminder: "Reminder", playerSupports: "Supports", playerNone: "Not chosen", playerComplete: "Lesson complete", playerCompleteBody: "You made time for yourself. Your next step is saved, ready when you are.", playerFinish: "Finish and save to My Toolkit", playerContinue: "Continue", playerStep: "step", playerResume: "Pick up where you left off", playerRelated: "Related practice", playerChoose: "Choose one to continue", playerSupportPrompt: "Who or what could support your next step?", playerReminderPrompt: "When would you like to try it?", playerTodayReminder: "Later today", playerTomorrowReminder: "Tomorrow", playerNoReminder: "No reminder", playerPractice: "Practice", playerTapOnly: "This step is tap-only. Listen only when you choose.", playerProtected: "Protected content", playerInsight: "One thing to remember",
} as const;
export const playerEs: Record<keyof typeof playerEn, string> = {
  playerBreathingType: "Respiración", playerTimerType: "Temporizador", playerChecklistType: "Lista", playerWorksheetType: "Hoja de práctica", playerMapperType: "Mapa", playerCalculatorType: "Calculadora", playerScaleType: "Escala", playerSeconds: "segundos", playerLibraryBack: "Volver a la biblioteca",
  playerConfidenceStart: "Elige tu nivel de confianza",
  playerListen: "Escuchar", playerVoice: "Leer en voz alta (voz simulada)", playerSlow: "Lento", playerNormal: "Normal", playerReplay: "Repetir", playerStop: "Detener", playerVoiceOff: "Lectura en voz alta apagada", playerVoiceUnavailable: "La lectura en voz alta no está disponible en este dispositivo.",
  playerDraft: "Español — Borrador", playerInhale: "Inhala", playerHold: "Mantén", playerExhale: "Exhala", playerCycle: "Ciclo", playerOf: "de", playerStart: "Comenzar", playerPause: "Pausa", playerDone: "Listo", playerReset: "Reiniciar", playerCues: "Indicaciones de respiración habladas", playerRounds: "rondas de respiración", playerSave: "Guardar en Mis herramientas", playerSaved: "Guardado en Mis herramientas", playerPurpose: "Propósito", playerMinutes: "minutos", playerRemove: "Quitar", playerAdd: "Agregar", playerLeft: "Lo que queda", playerMoneyIn: "Entra", playerMoneyOut: "sale", playerMoneyLeft: "queda", playerResponses: "Tu práctica está guardada.",
  playerSee: "ver", playerFeel: "sentir", playerHear: "oír", playerSmell: "oler", playerTaste: "saborear", playerThings: "Cosas que puedes", playerBack: "Atrás", playerNext: "Siguiente", playerQuestion: "Pregunta", playerReply: "Gracias por compartir. Un pequeño paso basta por hoy.", playerQuestion2: "¿Qué podría hacer esto más fácil?", playerQuestion3: "¿Qué pequeño paso te gustaría intentar?", playerSuggests: "Adel sugiere después", playerKeepTalking: "Seguir hablando con Adel", playerSimulated: "Simulado — Borrador", playerAnswer: "Tu respuesta", playerSend: "Compartir respuesta", playerToday: "Elige una acción para hoy", playerTodayHome: "La acción de hoy", playerConfidence: "¿Qué tanta confianza sientes?", playerUnanswered: "Sin responder", playerPreview: "Vista previa de tus herramientas", playerTool: "Herramienta", playerNextStep: "Siguiente paso", playerReminder: "Recordatorio", playerSupports: "Apoyos", playerNone: "Sin elegir", playerComplete: "Lección completa", playerCompleteBody: "Te dedicaste tiempo. Tu siguiente paso está guardado para cuando lo necesites.", playerFinish: "Terminar y guardar en Mis herramientas", playerContinue: "Continuar", playerStep: "paso", playerResume: "Continúa donde lo dejaste", playerRelated: "Práctica relacionada", playerChoose: "Elige una opción para continuar", playerSupportPrompt: "¿Quién o qué puede apoyar tu siguiente paso?", playerReminderPrompt: "¿Cuándo te gustaría intentarlo?", playerTodayReminder: "Más tarde hoy", playerTomorrowReminder: "Mañana", playerNoReminder: "Sin recordatorio", playerPractice: "Práctica", playerTapOnly: "Este paso se responde tocando. Escucha solo cuando tú decidas.", playerProtected: "Contenido protegido", playerInsight: "Algo para recordar",
};