// §Part B2 — My Care tile copy. Spanish pending bilingual review.
export const MY_CARE_TILE_COPY = {
  en: {
    apptTitle: "Your first appointment",
    scheduled: "Scheduled",
    notScheduled: "Not yet scheduled",
    notScheduledBody: "Your care team will reach out to set it up.",
    apptLink: "See appointments",
    needsTitle: "Your needs",
    matches: (n: number) => (n === 1 ? "1 place matches" : `${n} places match`),
    categoryOnly: "Your team will go over options",
    noMatch: "Your team will follow up",
    needsNote: "Looking is not the same as being referred — your team makes that connection.",
    needsLink: "See help that matches",
    recTitle: "Recommended for you",
    advTitle: "Advocate",
    advPending: "Invitation pending — sign consent to activate.",
    advLink: "Review consent",
  },
  es: {
    apptTitle: "Su primera cita",
    scheduled: "Programada",
    notScheduled: "Aún no programada",
    notScheduledBody: "Su equipo de cuidado se comunicará para programarla.",
    apptLink: "Ver citas",
    needsTitle: "Sus necesidades",
    matches: (n: number) => (n === 1 ? "1 lugar coincide" : `${n} lugares coinciden`),
    categoryOnly: "Su equipo revisará las opciones con usted",
    noMatch: "Su equipo le dará seguimiento",
    needsNote: "Buscar no es lo mismo que ser referido: su equipo hace esa conexión.",
    needsLink: "Ver ayuda que coincide",
    recTitle: "Recomendado para usted",
    advTitle: "Defensor",
    advPending: "Invitación pendiente: firme el consentimiento para activarla.",
    advLink: "Revisar consentimiento",
  },
} as const;
