import { useState } from "react";
import { useActingStaff } from "@/lib/roles";
import { staffContentInventory, inventoryCsv, contentRevisionDiff } from "@/lib/contentStaff";
import { contentMetrics, contentMetricCsv } from "@/lib/contentAnalytics";
import { contentType } from "@/lib/contentTypes";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Download } from "lucide-react";
function download(name: string, csv: string) { const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
export function ContentAudit({ version }: { version: number }) {
  const { role } = useActingStaff(); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [id, setId] = useState(""); const [before, setBefore] = useState("1"); const [after, setAfter] = useState("2");
  const inventory = staffContentInventory(role); const selected = inventory.find((e) => `${e.typeId}:${e.id}` === id); const a = selected?.revisions.find((r) => String(r.rev) === before), b = selected?.revisions.find((r) => String(r.rev) === after);
  return <section className="space-y-4" data-testid="content-audit" data-version={version}><div className="flex flex-wrap items-end gap-3"><label className="text-sm">From<Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label className="text-sm">To<Input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label><Button variant="outline" onClick={() => download("content-inventory.csv", inventoryCsv(role))}><Download className="mr-2 size-4" />Inventory CSV</Button><Button variant="outline" onClick={() => download("content-metrics.csv", contentMetricCsv(inventory.map((e) => ({ title: contentType(e.typeId).titleOf(e.body), type: e.typeId, id: e.id })), role, from, to))}><Download className="mr-2 size-4" />Aggregate CSV</Button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border">{["Content", "Starts", "Completions", "Completion rate", "Median rating change", "Care plans"].map((s) => <th key={s} className="p-2">{s}</th>)}</tr></thead><tbody>{inventory.filter((e) => ["library_lesson", "recovery_lesson", "exercise", "journey"].includes(e.typeId)).map((e) => { const m = contentMetrics(e.typeId, e.id, role, from, to); return <tr key={`${e.typeId}:${e.id}`} className="border-b border-border"><td className="p-2">{contentType(e.typeId).titleOf(e.body)}{m?.dropoff.map((d) => <p key={d.step} className="text-xs text-muted-foreground">Drop-off step {d.step + 1}: {d.count ?? "<11"}</p>)}</td>{[m?.starts, m?.completions, m?.rate, m?.medianChange, m?.planUsage].map((n, i) => <td key={i} className="p-2">{n ?? "<11"}</td>)}</tr>; })}</tbody></table></div><h3 className="font-semibold">Revision diff</h3><Select value={id} onValueChange={setId}><SelectTrigger aria-label="Revision item"><SelectValue placeholder="Choose an item" /></SelectTrigger><SelectContent>{inventory.map((e) => <SelectItem key={`${e.typeId}:${e.id}`} value={`${e.typeId}:${e.id}`}>{contentType(e.typeId).titleOf(e.body)}</SelectItem>)}</SelectContent></Select>{selected && <><div className="flex gap-2">{[[before, setBefore], [after, setAfter]].map(([value, set], i) => <Select key={i} value={value as string} onValueChange={set as (value: string) => void}><SelectTrigger aria-label={i ? "After revision" : "Before revision"} className="w-40"><SelectValue /></SelectTrigger><SelectContent>{selected.revisions.map((r) => <SelectItem key={r.rev} value={String(r.rev)}>Revision {r.rev}</SelectItem>)}</SelectContent></Select>)}</div>{a && b && <div className="space-y-2">{contentRevisionDiff(a.body, b.body).map((d) => <div key={d.field} className="border-b border-border py-2"><p className="font-medium">{d.field}</p><p className="break-words text-muted-foreground">{JSON.stringify(d.before)} → {JSON.stringify(d.after)}</p></div>)}</div>}</>}</section>;
}
