import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { metaOf, isPart2Content, spanishStatusOf } from "@/lib/contentGovernance";
import type { ContentEntry } from "@/lib/contentPublishing";
import { contentType } from "@/lib/contentTypes";
export function ContentInventoryTable({ entries, edit, review, canReview }: { entries: ContentEntry[]; edit: (id: string) => void; review: (ids: string[], reason: string) => void; canReview: boolean }) {
  const [selected, setSelected] = useState<string[]>([]); const [status, setStatus] = useState("all"); const [reason, setReason] = useState(""); const [flag, setFlag] = useState("all");
  return <section className="space-y-3"><div className="flex flex-wrap gap-2"><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-40" aria-label="Status filter"><SelectValue /></SelectTrigger><SelectContent>{["all", "draft", "pending_review", "published", "retired"].map((s) => <SelectItem key={s} value={s}>{s === "pending_review" ? "In review" : s === "published" ? "Live" : s}</SelectItem>)}</SelectContent></Select><Select value={flag} onValueChange={setFlag}><SelectTrigger className="w-40" aria-label="Manage flags"><SelectValue /></SelectTrigger><SelectContent>{["all", "part2", "clinical", "missing_es"].map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Input className="max-w-xs" aria-label="Review reason" placeholder="Reason for review" value={reason} onChange={(e) => setReason(e.target.value)} /><Button variant="outline" disabled={!canReview || !selected.length || !reason.trim()} onClick={() => { review(selected, reason); setSelected([]); }}>Mark reviewed ({selected.length})</Button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border">{["Select", "Title", "Type", "Status", "Part 2 / Clinical", "ES", "Owner", "Last reviewed", "Next review", ""].map((s, i) => <th key={i} className="p-2">{s}</th>)}</tr></thead><tbody>{entries.filter((e) => { const m = metaOf(e.body); return (status === "all" || status === "retired" ? status === "all" || !!(e.revisions.at(-1)?.action === "retired") : e.status === status && !(e.revisions.at(-1)?.action === "retired")) && (flag === "all" || flag === "part2" && isPart2Content(e.typeId, e.body) || flag === "clinical" && m.clinical || flag === "missing_es" && spanishStatusOf(e.body) === "missing"); }).map((e) => { const m = metaOf(e.body); return <tr key={e.id} className="border-b border-border"><td className="p-2"><Checkbox aria-label={`Select ${contentType(e.typeId).titleOf(e.body)}`} checked={selected.includes(e.id)} onCheckedChange={(v) => setSelected((ids) => v ? [...ids, e.id] : ids.filter((id) => id !== e.id))} /></td><td className="p-2" data-testid="managed-title">{contentType(e.typeId).titleOf(e.body)}</td><td className="p-2">{contentType(e.typeId).label}</td><td className="p-2">{(e.revisions.at(-1)?.action === "retired") ? "Retired" : e.status === "published" ? "Live" : e.status === "pending_review" ? "In review" : "Draft"}</td><td className="p-2">{isPart2Content(e.typeId, e.body) && <Badge variant="outline">Part 2</Badge>}{m.clinical && <Badge variant="secondary">Clinical</Badge>}</td><td className="p-2">{spanishStatusOf(e.body)}</td><td className="p-2">{m.owner || "Unassigned"}</td><td className="p-2">{m.lastReviewed || "Not set"}</td><td className="p-2">{m.nextReview || "Not set"}</td><td className="p-2"><Button variant="outline" size="sm" disabled={e.status === "pending_review"} onClick={() => edit(e.id)}>Edit</Button></td></tr>; })}</tbody></table></div></section>;
}
