import { test, expect } from "@playwright/test";
test.use({ viewport: { width: 1280, height: 1800 } });
test("staff library privately previews actual players, manages exercises and audits aggregates", async ({ page }) => {
 test.setTimeout(150_000);
 await page.goto("/clinician");
 await page.waitForFunction(() => !!(window as any).__adelante, null, { timeout: 60_000 });
 await page.evaluate(() => { const app = (window as any).__adelante; app.setActingStaff("s-np1", "pmhnp"); app.go("/content-library"); });
 const browse = page.getByTestId("content-browse"); await expect(browse).toBeVisible();
 await expect(page.locator('a[data-nav-id="content-library"]')).toContainText("Content library");
 const before = await page.evaluate(async () => { const app = (window as any).__adelante; const { eng } = await app.content(); return JSON.stringify(eng.getEngagement(app.AdelanteEHR.getCurrentPatientId())); });
 await page.getByRole("combobox", { name: "Browse type", exact: true }).click(); await page.getByRole("option", { name: "Education", exact: true }).click();
 await browse.getByRole("button", { name: "Preview", exact: true }).first().click();
 const preview = page.getByTestId("private-content-preview"); await expect(preview).toContainText("Preview — nothing is saved");
 await expect(preview.locator(".patient-theme").first()).toBeVisible();
 await expect(preview.getByText("Read aloud (Simulated voice)").first()).toBeVisible();
 await preview.getByRole("button", { name: "ES · Draft", exact: true }).click();
 await expect(preview.getByRole("button", { name: "ES · Draft", exact: true })).toHaveAttribute("aria-pressed", "true");
 await preview.screenshot({ path: "/tmp/browser/staff-content-preview.png" });
 await page.keyboard.press("Escape");
 const after = await page.evaluate(async () => { const app = (window as any).__adelante; const { eng } = await app.content(); return JSON.stringify(eng.getEngagement(app.AdelanteEHR.getCurrentPatientId())); });
 expect(after).toBe(before);
 await page.evaluate(() => { const app = (window as any).__adelante; app.setActingStaff("s-cc2", "clinical_coordinator"); app.go("/admin-content"); });
 await page.getByRole("tab", { name: "Manage", exact: true }).click(); await page.getByTestId("content-groups").getByRole("button", { name: "Exercises", exact: true }).click();
 await expect(page.getByTestId("managed-title").filter({ hasText: "Box Breathing" }).first()).toBeVisible();
 await page.getByTestId("managed-title").filter({ hasText: "Box Breathing" }).first().locator("..").getByRole("button", { name: "Edit", exact: true }).click();
 await expect(page.getByRole("dialog")).toContainText("Structured exercise"); await page.getByRole("textbox", { name: "Content change reason", exact: true }).fill("Reviewed breathing phases with provider — Draft");
 await page.getByRole("button", { name: "Save draft", exact: true }).click(); await expect(page.getByText("Draft saved. Patients still see the published version, if any.", { exact: true }).first()).toBeVisible();
 await page.keyboard.press("Escape"); await page.getByRole("tab", { name: "Audit", exact: true }).click(); await expect(page.getByTestId("content-audit")).toContainText("<11");
 await page.getByTestId("content-audit").screenshot({ path: "/tmp/browser/staff-content-audit.png" });
});
