/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ClinicianProfileRouteImport } from './routes/clinician-profile'
import { Route as ClinicianRouteImport } from './routes/clinician'
import { Route as CaseManagerRouteImport } from './routes/case-manager'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminVendorsRouteImport } from './routes/admin-vendors'
import { Route as AdminAuditRouteImport } from './routes/admin-audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianProfileRoute = ClinicianProfileRouteImport.update({
  id: '/clinician-profile',
  path: '/clinician-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianRoute = ClinicianRouteImport.update({
  id: '/clinician',
  path: '/clinician',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseManagerRoute = CaseManagerRouteImport.update({
  id: '/case-manager',
  path: '/case-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin-vendors',
  path: '/admin-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin-audit',
  path: '/admin-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-audit': typeof AdminAuditRoute
  '/admin-vendors': typeof AdminVendorsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/case-manager': typeof CaseManagerRoute
  '/clinician': typeof ClinicianRoute
  '/clinician-profile': typeof ClinicianProfileRoute
  '/consent': typeof ConsentRoute
  '/home': typeof HomeRoute
  '/intake': typeof IntakeRoute
  '/patient': typeof PatientRoute
  '/referral': typeof ReferralRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-audit': typeof AdminAuditRoute
  '/admin-vendors': typeof AdminVendorsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/case-manager': typeof CaseManagerRoute
  '/clinician': typeof ClinicianRoute
  '/clinician-profile': typeof ClinicianProfileRoute
  '/consent': typeof ConsentRoute
  '/home': typeof HomeRoute
  '/intake': typeof IntakeRoute
  '/patient': typeof PatientRoute
  '/referral': typeof ReferralRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-audit': typeof AdminAuditRoute
  '/admin-vendors': typeof AdminVendorsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/case-manager': typeof CaseManagerRoute
  '/clinician': typeof ClinicianRoute
  '/clinician-profile': typeof ClinicianProfileRoute
  '/consent': typeof ConsentRoute
  '/home': typeof HomeRoute
  '/intake': typeof IntakeRoute
  '/patient': typeof PatientRoute
  '/referral': typeof ReferralRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-audit'
    | '/admin-vendors'
    | '/auth'
    | '/billing'
    | '/case-manager'
    | '/clinician'
    | '/clinician-profile'
    | '/consent'
    | '/home'
    | '/intake'
    | '/patient'
    | '/referral'
    | '/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-audit'
    | '/admin-vendors'
    | '/auth'
    | '/billing'
    | '/case-manager'
    | '/clinician'
    | '/clinician-profile'
    | '/consent'
    | '/home'
    | '/intake'
    | '/patient'
    | '/referral'
    | '/schedule'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-audit'
    | '/admin-vendors'
    | '/auth'
    | '/billing'
    | '/case-manager'
    | '/clinician'
    | '/clinician-profile'
    | '/consent'
    | '/home'
    | '/intake'
    | '/patient'
    | '/referral'
    | '/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  CaseManagerRoute: typeof CaseManagerRoute
  ClinicianRoute: typeof ClinicianRoute
  ClinicianProfileRoute: typeof ClinicianProfileRoute
  ConsentRoute: typeof ConsentRoute
  HomeRoute: typeof HomeRoute
  IntakeRoute: typeof IntakeRoute
  PatientRoute: typeof PatientRoute
  ReferralRoute: typeof ReferralRoute
  ScheduleRoute: typeof ScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician-profile': {
      id: '/clinician-profile'
      path: '/clinician-profile'
      fullPath: '/clinician-profile'
      preLoaderRoute: typeof ClinicianProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician': {
      id: '/clinician'
      path: '/clinician'
      fullPath: '/clinician'
      preLoaderRoute: typeof ClinicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-manager': {
      id: '/case-manager'
      path: '/case-manager'
      fullPath: '/case-manager'
      preLoaderRoute: typeof CaseManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-vendors': {
      id: '/admin-vendors'
      path: '/admin-vendors'
      fullPath: '/admin-vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-audit': {
      id: '/admin-audit'
      path: '/admin-audit'
      fullPath: '/admin-audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  CaseManagerRoute: CaseManagerRoute,
  ClinicianRoute: ClinicianRoute,
  ClinicianProfileRoute: ClinicianProfileRoute,
  ConsentRoute: ConsentRoute,
  HomeRoute: HomeRoute,
  IntakeRoute: IntakeRoute,
  PatientRoute: PatientRoute,
  ReferralRoute: ReferralRoute,
  ScheduleRoute: ScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
